#+TITLE: Algebra
#+AUTHOR: Yellowflash

#+INCLUDE: "./Notes.layout"

* Law of composition, associativity and commutativity
** Law of composition
   + Given a set $E$ with a function $f$ from $E \times E$ to $E$ is called law of composition.
   + A value $f(x,y)$ for $x,y \in E$ is called composition of $(x,y)$.
   + A set with a law of composition is called magma.
   + Let $E$ be a magma $+$ denoting the law of composition, then the magma with the composition law $(x,y) \rightarrow y + x$ is called opposite magma.
   + Given $(A, .)$ and $(B, +)$ be two magmas, the function $f$ from $A \rightarrow B$ is called homomorphism if $f(x . y) = f(x) + f(y)$ for all $x,y \in A$.
   + If $A = B$ in above definition its called endomorphism.
   + If $f$ is one-to-one and onto its called isomorphism.
** Composition of ordered sequence of elements
   + A finite family of elements of $E$ whose indexing set $I$ is totally ordered is called ordered sequence of elements.
   + Given $(x_{\alpha})_{\alpha \in A}$ be the ordered sequence of elements of magma $E$ whose indexing set $A$ is non-empty.
     + The composition of such ordered sequence of elements $\Sigma_{\alpha \in A} x_{\alpha}$ is inductively defined on the number of elements of $A$ .
     + $= x_{\beta}$ if $A = \{\beta\}$
     + $= x_{\beta} + \Sigma_{\alpha \in A'} x_{\alpha}$ where $\beta$ is the smallest element and $A' = A - \{\beta\}$  (With the same ordering).
   + Homomorphism preserves composition of ordered sequences (Proof?)
** Associative laws
   + A law of composition $+$ in $E$ is called associative if $x + (y + z) = (x + y) + z$ for all $x,y,z \in E$.
   + Opposite law of an associative law is associative.
   + Associativity theorem (Partition order sequences in a such that each partition is ordered too, then by associativity the composition on orginal sequence is same as composition of the composition of individual partitions)
** Stable subsets and induced laws
   + A subset $A$ of $E$ is called stable subset if $x + y \in A$ for all $x, y \in A$
   + Such a subset with induced composition law is called submagma.
   + Intersection of family of stable subsets is stable (Proof?).
   + Smallest stable subset containing a given subset $X$ is said to generated by $X$.
   + Let $E$ and $F$ be two magmas and $f$ be a homomorphism between them then,
     + Image of stable subset of $E$ by $f$ is a stable subset of $F$.
     + Inverse image of a stable subset of $F$ by $f$ is a stable subset of $E$.
     + If $X$ is subset of $E$ the image of stable subset of $E$ is same as the stable subset generated by $f(X)$
     + If $g$ is another homomorphism, then the set of elements $x \in E$ such that $f(x) = g(x)$ forms a stable subset.
** Permutable elements, commutative law
   + Given magma $(E, +)$, $x,y \in E$ is said to commute if $x + y = y + x$ 
   + A magma is said to be commutative if every pair of elements commute.
   + A commutative law is equal to its opposite.
   + Let $X$ be a subset of $E$ then if set of element of *$E$* which commutes with each element of $X$ is called centralizer of $X$.
